name: "Extract Regex"
description: "A GitHub Action to extract a regex pattern from a string"
inputs:
  regex:
    description: "The regex pattern to extract"
    required: true
  flags:
    description: "The regex flags to use"
    required: false
  input:
    description: "The input string to extract from"
    required: true
outputs:
  resultString:
    description: "The extracted matches as a string"
  resultArray:
    description: "The extracted matches as an array"
runs:
  using: "node16"
  main: "dist/index.js"
